name: Configure Branch Protection

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]
    paths: ['.github/workflows/branch-protection.yml']

jobs:
  setup-branch-protection:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Setup Branch Protection Rules
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const owner = context.repo.owner;
            const repo = context.repo.repo;
            
            // Configure main branch protection
            await github.rest.repos.updateBranchProtection({
              owner,
              repo,
              branch: 'main',
              required_status_checks: {
                strict: true,
                contexts: [
                  'provisioning-service-ci',
                  'docker-build', 
                  'integration-tests',
                  'security-scan',
                  'quality-gate',
                  'commit-validation-summary'
                ]
              },
              enforce_admins: false,
              required_pull_request_reviews: {
                required_approving_review_count: 1,
                dismiss_stale_reviews: true,
                require_code_owner_reviews: true,
                require_last_push_approval: true
              },
              restrictions: null,
              allow_force_pushes: false,
              allow_deletions: false,
              block_creations: false,
              required_conversation_resolution: true
            });
            
                          // Configure develop branch protection (if exists)
              try {
                await github.rest.repos.updateBranchProtection({
                  owner,
                  repo,
                  branch: 'develop',
                  required_status_checks: {
                    strict: true,
                    contexts: [
                      'provisioning-service-ci',
                      'docker-build',
                      'integration-tests',
                      'security-scan',
                      'commit-validation-summary'
                    ]
                  },
                enforce_admins: false,
                required_pull_request_reviews: {
                  required_approving_review_count: 1,
                  dismiss_stale_reviews: true
                },
                restrictions: null,
                allow_force_pushes: false,
                allow_deletions: false
              });
            } catch (error) {
              console.log('Develop branch does not exist or protection already configured');
            }
            
            console.log('Branch protection rules configured successfully');